# Используем JDK 21
FROM eclipse-temurin:21-jdk

WORKDIR /app

# Копируем весь проект
COPY PPO_f PPO_f

# Даем права на gradlew
RUN chmod +x PPO_f/gradlew

WORKDIR /app/PPO_f

# Переменная окружения для Spring Boot, чтобы использовался профиль test
ENV SPRING_PROFILES_ACTIVE=test

# Тесты будем запускать из CI/CD через команду:
# bash -c "./gradlew :app_cli:test -Dorg.gradle.report.outputDir=/app/test-results"
