#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=werb3klmo
#
## JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#server.port=9099
#server.address=127.0.0.1
#
#olama-host = http://localhost:11434/api/generate
#ml.api.url=http://localhost:11434/api/generate
#ml.api.content-type=application/json
#
#logging.level.ru.bmstu.iu7=INFO
#logging.file.name=D:/Projects/PPO_f/PPO_f/ppo_f.log
#logging.console.enabled=false
#spring.data.mongodb.uri=mongodb://localhost:27017/ppo_f

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE




## SQLite datasource
#spring.datasource.url=jdbc:sqlite:./ppo_f.db
#spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.datasource.username=
#spring.datasource.password=
#
## JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLiteDialect
#
## Server
#server.port=9099
#server.address=127.0.0.1
#
## External APIs
#olama-host=http://localhost:11434/api/generate
#ml.api.url=http://localhost:11434/api/generate
#ml.api.content-type=application/json
#
## Logging
#logging.level.ru.bmstu.iu7=INFO
#logging.file.name=D:/Projects/PPO_f/PPO_f/ppo_f.log
#logging.console.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=werb3klmo

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=9099
server.address=127.0.0.1

olama-host = http://localhost:11434/api/generate
ml.api.url=http://localhost:11434/api/generate
ml.api.content-type=application/json
