name: Tests (Unit + Integration)

on:
  pull_request:
    branches: [ main, lab2 ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb" 
          --health-interval 5s 
          --health-timeout 5s 
          --health-retries 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image for integration tests
      run: docker build -t integration-tests-image -f ./Dockerfile.integration .

    - name: Run integration tests and generate Allure report
      run: |
        mkdir -p ${{ github.workspace }}/PPO_f/build/allure-results
        mkdir -p ${{ github.workspace }}/PPO_f/build/reports/allure-report

        docker run --rm \
          --network host \
          -e POSTGRES_HOST=localhost \
          -e POSTGRES_PORT=5432 \
          -e POSTGRES_USER=testuser \
          -e POSTGRES_PASSWORD=testpassword \
          -e POSTGRES_DB=testdb \
          -v ${{ github.workspace }}/PPO_f/build/allure-results:/app/PPO_f/build/allure-results \
          -v ${{ github.workspace }}/PPO_f/build/reports/allure-report:/app/PPO_f/build/reports/allure-report \
          integration-tests-image

    - name: Upload Allure HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-integration
        path: PPO_f/build/reports/allure-report

