name: Tests (Unit + Integration)

on:
  pull_request:
    branches: [ main, lab2 ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for integration tests
        run: docker build -t bd-integration-tests -f ./Dockerfile.integration .

      - name: Run integration tests in Docker
        run: |
          mkdir -p ${{ github.workspace }}/PPO_f/test-results/integration
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/PPO_f/test-results/integration:/app/test-results \
            bd-integration-tests \
            bash -c "mkdir -p /app/test-results && ./gradlew :app_cli:test --stacktrace --info -Dorg.gradle.report.outputDir=/app/test-results"

      - name: Upload integration test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-reports
          path: PPO_f/test-results/integration
